### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by rbrv** [nystudio107/craft-code-editor#2]
As mentioned in https://github.com/putyourlightson/craft-sprig/issues/308, I stumbled upon the fact that the craft-code-editor package is pretty big (`51.4MB`).

As mentioned by @bencroker in [that issue](https://github.com/putyourlightson/craft-sprig/issues/308#issuecomment-1543892149), there seem to  be "lots of potential duplicate files at https://github.com/nystudio107/craft-code-editor/tree/develop/src/web/assets/dist that could possibly be excluded".

**Comment by khalwat** [comment]
Happy to hear what you think potentially could be excluded?

The Monaco Editor that it uses is relatively large, and because it needs to work with arbitrary languages, we can't know ahead of time what should or should not be excluded.

But if there's something you think shouldn't be there, or truly isn't needed, feel free to let me know.

**Comment by rbrv** [comment]
Thanks for the clarification.  
I have no idea what could be excluded, was just following up on a suggestion of @bencroker.

**Comment by khalwat** [comment]
I guess my follow-up would be what are your concerns re: the bundle size?

In the CP, it only loads what is needed.

Are you concerned about the download time? Or the size on disk?

**Comment by rbrv** [comment]
Main concern was size on disk, in the context of the craft-sprig plugin. In this plugin craft-code-editor accounts for 99.4% of the disk space.

**Comment by khalwat** [comment]
Well, it's likely that you will be using it on production, if you use CKEditor or SEOmatic or other such things.

What is the concern about disk space? Are you actually running out of disk space on shared hosting or something?
