### ISSUE TITLE
Unable to update fields separately if there's more than one on a page

### ISSUE THREAD

**Issue by d-karstens** [nystudio107/craft-code-editor#4]
### Describe the bug
Hi, after updating to 1.0.12 we encountered an issue where changing the value of a field in SEOmatic caused it to change for all of them - I noticed this in SEOmatic, but confirmed the behaviour was also happening in a module of our own that uses code editor fields

### To reproduce
Steps to reproduce the behaviour:
1. Have two or more Code Editor fields on a page
2. Attempt to change the value of one of them and see the other field change too

### Screenshots
I've recorded a short video of this happening
https://github.com/nystudio107/craft-code-editor/assets/21274925/760b8d6d-99bf-44cf-a3a6-014c415ac90a

### Versions
- Plugin version: 1.0.12
- Craft version: 4.4.17

**Comment by khalwat** [comment]
Ah man. Yeah I know what this is. Thanks, I will roll it back.

**Comment by khalwat** [comment]
Okay, I released a new version of `craft-code-editor` to fix it. You can do:

```
composer update nystudio107/craft-code-editor
```

...to fix it.

https://github.com/nystudio107/craft-code-editor/releases/tag/1.0.13

**Comment by d-karstens** [comment]
Cheers for the quick fix!
