### ISSUE TITLE
Using multiple instances on the same page?

### ISSUE THREAD

**Issue by vaughn-taylor** [nystudio107/craft-code-editor#6]
### Question
How do I use more than one instance of the Code Editor on the same page? 

### Additional context
I'm using your Code plugin to create snippets of sample code which are rendered in my front end template. If possible, I'd like to avoid adding additional code highlighters like Shiki, highlighter.js, etc and instead use craft-code-editor. I can output a single field using the example code provided:

    <textarea id="myCode">{{ entry.codeEditor.value | raw }}</textarea>
    {{ codeEditor.includeJs("myCode", "Frontend Editor", {
        language: entry.codeEditor.language,
        theme: "auto",
        "domReadOnly": true,
        "readOnly": true
    }) }}

This works for the first instance – I'm seeing a VisualCode looking field on the front-end. But, only the first field renders properly. I assume this is because there's an ID conflict? So, I added a loop index like this:

    <textarea id="myCode_{{ loopIndex }}">{{ entry.codeEditor.value | raw }}</textarea>
    {{ codeEditor.includeJs("myCode_{{ loopIndex }}", "Frontend Editor", {
        language: entry.codeEditor.language,
        theme: "auto",
        "domReadOnly": true,
        "readOnly": true
    }) }}

Which produces a unique ID for each textarea:

    <textarea id="myCode_1">...</textarea>    
    <textarea id="myCode_2">...</textarea>

However, none of the fields render properly. I'm just seeing un-styled textarea fields.

**Comment by khalwat** [comment]
This is an error in your Twig code. This code:

```twig
<textarea id="myCode_{{ loopIndex }}">{{ entry.codeEditor.value | raw }}</textarea>
{{ codeEditor.includeJs("myCode_{{ loopIndex }}", "Frontend Editor", {
    language: entry.codeEditor.language,
    theme: "auto",
    "domReadOnly": true,
    "readOnly": true
}) }}
```

Will render the first parameter to `includeJs()` to be `myCode_{{ loopIndex }}` because you're already in Twig code, so the `{{ }}` will just output those literal characters. You want something like this instead: `myCode_#{loopIndex}` that uses Twig string interpolation: https://twig.symfony.com/doc/3.x/templates.html#string-interpolation
