### ISSUE TITLE
Cannot use ::class with dynamic class name

### ISSUE THREAD

**Issue by ArpadGBondor** [nystudio107/craft-code-editor#7]
### Describe the bug
We keep getting an error thrown from this package:
Cannot use ::class with dynamic class name

It is coming from here:
/nystudio107/craft-code-editor/src/autocompletes/SectionShorthandFieldsAutocomplete.php:167

I think it is this line in the current version:
https://github.com/nystudio107/craft-code-editor/blob/d2d9c8706fc1a6f40253fc78762101ce9b5ac386/src/autocompletes/SectionShorthandFieldsAutocomplete.php#L174

### Expected behaviour
I think something like this would solve it:
https://github.com/nystudio107/craft-twigfield/commit/bff508e2e239fd55b8a17ea56fc60db5e655f418

### Versions
- Plugin version:
    "nystudio107/craft-seomatic": "3.4.68",
- Craft version:
    "craftcms/cms": "3.8.5",
   PHP - 7.4.33

**Comment by khalwat** [comment]
I'm sorry I somehow missed this issue, thanks for re-filing it under SEOmatic to get my attention.

**Comment by khalwat** [comment]
Addressed via https://github.com/nystudio107/craft-code-editor/commit/c8c04db13fcabbe31e3f5d04b828b04c37afe577

**Comment by khalwat** [comment]
Fixed in version `1.0.18` -> https://github.com/nystudio107/craft-code-editor/releases/tag/1.0.18

You can update via:

```
composer update nystudio107/craft-code-editor
```
