### ISSUE TITLE
CSS overrides classes in other stylesheets

### ISSUE THREAD

**Issue by spoeken** [nystudio107/craft-code-editor#9]
### Describe the bug
The css that gets imported when using `{{ codeEditor.includeJs('code-editor') }}` overrides other stylesheets. 
For instance when using tailwind and media queries. i.e. `.hidden` overrides tailwinds `md:inline-block`.

### To reproduce
Steps to reproduce the behaviour:
1. Use the includeJs function in a template `{{ codeEditor.includeJs('code-editor') }}`
2. Import tailwind css in head
3. Add the classes `hidden` and `md:inline-block` to an element in the template

### Expected behaviour
I would expect that the css included would not influence anything else than the code-block element. 

### Suggestion
It would be nice to be able to only import the js, without defining an ID and without importing the CSS

### Versions
- Plugin version:
craft-code-editor: ^1.0.11
required by
craft-code-field: 4.0.12

- Craft version:
4.7.0

**Comment by khalwat** [comment]
Unfortunately this comes from the upstream Monaco package, so AFAIK, there isn't anything I can really do about it.

It uses this webpack plugin to do the build:

https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin

If you're able to figure out a way to adjust the namespacing of the CSS it uses or such, I'd happily accept a PR to do it!

**Comment by khalwat** [comment]
Turns out this was actually coming from _my_ CSS, which I do have control over!

See this issue: https://github.com/nystudio107/craft-code-editor/issues/8

**Comment by khalwat** [comment]
Fixed in version `1.0.18` -> https://github.com/nystudio107/craft-code-editor/releases/tag/1.0.18

You can update via:

```
composer update nystudio107/craft-code-editor
```
